<?php
    //DEFAULT FILEMANAGER RESOURCES FILE
    $GLOBALS['FILEMANAGER_RESOURCES'] = array(
        'directory'=>'directory'
        ,'file'=>'file'
        ,'size'=>'dimensione'
        ,'dimensions'=>'dimensioni'
        ,'created'=>'creato'
        ,'modified'=>'modificato'
        ,'rename'=>'rinomina'
        ,'name'=>'nome'
        ,'back'=>'indietro'
        ,'search'=>'cerca'
        ,'close'=>'chiudi'
        ,'ok'=>'Ok'
        ,'add_folder'=>'Aggiungi cartella'
        ,'add_file'=>'Nuovo file'
        ,'no_folders'=>'Nessuna cartella presente'
        ,'no_files'=>'Nessun file presente'
        ,'invalid_name'=>'Nome non valido'
        ,'error'=>'Errore'
        ,'error:missingFileName'=>'Nome file mancante'
        ,'error:acceptFileTypes'=>'Tipo di file non valido'
        ,'error:maxFileSize'=>'File troppo grande'
        ,'error:maxNumberOfFiles'=>'Numero massimo di files superato'
        ,'confirm_delete'=>'Conferma cancellazione?'
        ,'right-click for options'=>'tasto destro per opzioni'
        ,'pick_file'=>'scegli il file'
        ,'delete'=>'elimina'
        ,'download'=>'download'
        ,'preview'=>'anteprima'
        ,'large_view'=>'icone grandi'
        ,'details'=>'dettagli'
    )
?>